### ISSUE TITLE
Booking form

### ISSUE THREAD

**Issue by Theklinto** [Theklinto/klintdev-wpbooking#18]
Create booking form that allows for customers to book on webpage

### Tasks:
- [ ] Define and create database tables
- [ ] Form part: Calendar
- [ ] Form part: Select room + package 
- [ ] Form part: Contact information
   - Remember to accept terms and condition + rental contract
- [ ] Form part: Redirect to payment provider
- [ ] Form part: Confirmation page
- [ ] Form part: Error page
- [ ] Send email on confirmation
